package com.undsf.brak.crawler.tags

class Character(
    var Id: Int? = null,
    var Name: String? = null,
    var JPName: String? = null,
    var JPReading: String? = null,
    var School: String? = null,
    var Club: String? = null,
    var Age: String? = null,
    var Birthday: String? = null,
    var Height: String? = null,
    var Hobbies: String? = null,
    var WeaponType: String? = null,
    var UsesCover: String? = null,
    var Rarity: Int? = null,
    var CombatClass: String? = null,
    var ArmorType: String? = null,
    var AttackType: String? = null,
    var Position: String? = null,
    var Role: String? = null,
    var CityTownAffinity: String? = null,
    var OutdoorAffinity: String? = null,
    var IndoorAffinity: String? = null,
    var EquipmentSlot1: String? = null,
    var EquipmentSlot2: String? = null,
    var EquipmentSlot3: String? = null,
    var CharacterPool: String? = null,
    var ReleaseDate: String? = null,
)
